### ISSUE TITLE
メッセージを「Message.csv」ではなく、「Resources.resx」で管理するように修正

### ISSUE THREAD

**Issue by tsushoji** [tsushoji/AutoReportAppProject#4]

**Comment by re3assist** [comment]
確認しました。特に指摘はありません。
このぐらいの規模であればMessageを管理するクラスを作るより共通化を考えずに各々処理に対応したメッセージを呼び出すほうがシンプルで良いですね！

**Comment by tsushoji** [comment]
アドバイスありがとうございます。
上記のように実装していこうと考えます。
